version: "3.9"
services:
  app:
    build: .
    ports:
      - "8085:8081"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    #    shm_size: 128mb
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=PruebasDocker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db
volumes:
  db_data: